// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXP9cL7IkTSDz4ktmTTC0sqlvk_aKIrDM',
    appId: '1:96109437303:web:77d1ba11220b71ec980172',
    messagingSenderId: '96109437303',
    projectId: 'auth-cloud-todo',
    authDomain: 'auth-cloud-todo.firebaseapp.com',
    storageBucket: 'auth-cloud-todo.firebasestorage.app',
    measurementId: 'G-7KZKK5HMZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmu-h7jvs8btBJLmcmyXHcfczI3Tug_qA',
    appId: '1:96109437303:android:ffe7bc6cec58ff44980172',
    messagingSenderId: '96109437303',
    projectId: 'auth-cloud-todo',
    storageBucket: 'auth-cloud-todo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc68umhMjhfpW_fJdZdLKt0C5V_KAQeJA',
    appId: '1:96109437303:ios:1b3680aec995894e980172',
    messagingSenderId: '96109437303',
    projectId: 'auth-cloud-todo',
    storageBucket: 'auth-cloud-todo.firebasestorage.app',
    iosBundleId: 'com.example.toDoListAppFire2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc68umhMjhfpW_fJdZdLKt0C5V_KAQeJA',
    appId: '1:96109437303:ios:1b3680aec995894e980172',
    messagingSenderId: '96109437303',
    projectId: 'auth-cloud-todo',
    storageBucket: 'auth-cloud-todo.firebasestorage.app',
    iosBundleId: 'com.example.toDoListAppFire2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXP9cL7IkTSDz4ktmTTC0sqlvk_aKIrDM',
    appId: '1:96109437303:web:30adcd1b5ffa84a4980172',
    messagingSenderId: '96109437303',
    projectId: 'auth-cloud-todo',
    authDomain: 'auth-cloud-todo.firebaseapp.com',
    storageBucket: 'auth-cloud-todo.firebasestorage.app',
    measurementId: 'G-567PXRFDRS',
  );
}
